### ISSUE TITLE
Problem converting from Ease to SV

### ISSUE THREAD

**Issue by mgazdziak** [medgooroo/convertifer#2]
Tried to convert from an EASE Focus file:

![image](https://github.com/medgooroo/convertifer/assets/160767284/cece0cac-3107-4b26-9a3a-a70572fc07a4)

The SV file doesn't quite match:

![image](https://github.com/medgooroo/convertifer/assets/160767284/7af54294-689f-4f84-805b-404db86946bd)

**Comment by medgooroo** [comment]
I've pushed a fix - try again and let me know if it works? 
( There is a First Direct model in the L-acoustics venue database... altthough its marked as being in the US: 
https://www.l-acoustics.com/documentation/VENUE%20DATABASE/First%20Direct%20Arena/UK%20LEEDS%20FIRST%20DIRECT%20ARENA.xmls 
 )

**Comment by mgazdziak** [comment]
Looks like that fixed it, thank you!
Good catch on the SV database file, that Leeds venue looks like it matches.
